## Data Preprocessing

### 1. Load the libraries

In [18]:
import pandas as pd

### 2. Load the dataset

In [19]:
df = pd.read_csv(r'C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\UNSW-NB15.csv', low_memory=False)
pd.set_option('display.max_columns', None)
df.sample(15)

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1717152,175.45.176.1,47439,149.171.126.18,53,udp,INT,0.000009,114,0,254,0,0,0,dns,5.066666e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424239201,1424239201,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,,39,39,33,33,33,15,39,Generic,1
2054841,59.166.0.6,32800,149.171.126.1,5190,tcp,FIN,0.148440,1244,2574,31,29,4,4,-,6.289410e+04,1.310159e+05,16,18,255,255,693891948,2839612235,78,143,0,0,626.141339,16.203723,1424248203,1424248204,9.858800,8.694471,0.000767,0.000625,0.000142,0,0,NaN,NaN,,3,1,2,3,1,1,1,NaN,0
2322563,59.166.0.2,5938,149.171.126.8,53,udp,CON,0.001008,146,178,31,29,0,0,dns,5.793651e+05,7.063492e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424255862,1424255862,0.004000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,3,4,5,5,2,1,1,NaN,0
2488341,59.166.0.2,26317,149.171.126.4,24540,tcp,FIN,0.055140,4550,72346,31,29,7,33,-,6.517229e+05,1.036518e+07,78,80,255,255,2324193461,192150553,58,904,0,0,43.628672,42.626437,1424260769,1424260769,0.712130,0.700769,0.000602,0.000477,0.000125,0,0,NaN,NaN,,10,1,4,8,1,1,1,NaN,0
2499014,59.166.0.4,26924,149.171.126.4,111,udp,CON,0.284242,568,304,31,29,0,0,-,1.198978e+04,6.417067e+03,4,4,0,0,0,0,142,76,0,0,126.784953,33.886207,1424261005,1424261005,89.659000,23.965666,0.000000,0.000000,0.000000,0,0,NaN,NaN,,4,5,5,3,1,1,4,NaN,0
915858,59.166.0.6,11574,149.171.126.8,9626,tcp,FIN,0.027460,3614,48202,31,29,7,24,-,1.035397e+06,1.382345e+07,60,64,255,255,3078235913,3100015380,60,753,0,0,23.940830,23.261759,1421965223,1421965223,0.466879,0.428127,0.000626,0.000485,0.000141,0,0,0.0,0.0,0,4,8,3,4,1,1,2,NaN,0
2389518,59.166.0.9,19830,149.171.126.6,53,udp,CON,0.001087,146,178,31,29,0,0,dns,5.372585e+05,6.550138e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424258595,1424258595,0.008000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,2,2,4,1,1,1,2,NaN,0
2079675,59.166.0.8,20784,149.171.126.0,80,tcp,FIN,1.039240,1580,10168,31,29,3,5,http,1.115430e+04,7.393095e+04,12,18,255,255,2166311655,2171476986,132,565,1,3924,9561.991236,7699.894020,1424249194,1424249195,94.444000,61.100591,0.000650,0.000526,0.000124,0,0,1.0,NaN,,1,1,1,4,1,1,1,NaN,0
2329406,59.166.0.3,22464,149.171.126.1,47019,udp,CON,0.001560,528,304,31,29,0,0,-,2.030769e+06,1.169231e+06,4,4,0,0,0,0,132,76,0,0,0.558143,0.255501,1424256121,1424256121,0.397667,0.182667,0.000000,0.000000,0.000000,0,0,NaN,NaN,,5,11,5,4,1,1,5,NaN,0
1969653,149.171.126.15,1043,175.45.176.3,53,udp,INT,0.000004,264,0,60,0,0,0,dns,2.640000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424246233,1424246233,0.004000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,22,22,22,22,22,22,22,NaN,0
290463,59.166.0.3,60820,149.171.126.7,111,udp,CON,0.004626,568,304,31,29,0,0,-,7.367056e+05,3.942931e+05,4,4,0,0,0,0,142,76,0,0,1.763289,1.461119,1421939104,1421939104,1.251333,1.036667,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,4,2,1,2,1,1,1,NaN,0
2336706,10.40.182.6,138,10.40.182.255,138,udp,INT,0.000079,503,0,64,0,0,0,-,2.551899e+07,0.000000e+00,2,0,0,0,0,0,252,0,0,0,0.000000,0.000000,1424256414,1424256414,0.079000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,3,3,3,3,3,3,3,NaN,0
1737674,59.166.0.1,9375,149.171.126.8,46000,tcp,FIN,0.261675,4096,2872,31,29,7,7,-,1.204242e+05,8.444062e+04,26,26,255,255,62398259,65808955,158,110,0,0,648.339333,17.529848,1424239666,1424239666,10.454600,10.444520,0.000689,0.000557,0.000132,0,0,NaN,NaN,,5,6,7,4,1,1,4,NaN,0
1086355,59.166.0.0,53547,149.171.126.4,21,tcp,FIN,0.391961,2934,3740,31,29,11,15,ftp,5.874054e+04,7.492582e+04,52,54,255,255,2594830055,2592122662,56,69,0,0,972.513998,37.643258,1421972685,1421972685,7.679216,7.384094,0.000750,0.000593,0.000157,0,0,0.0,1.0,1,1,2,3,3,1,1,2,NaN,0
51743,59.166.0.1,57739,149.171.126.9,53,udp,CON,0.001054,146,178,31,29,0,0,dns,5.540797e+05,6.755218e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421929477,1421929477,0.011000,0.012000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,5,6,2,3,2,1,1,NaN,0

### 3. Datatypes of the features

In [20]:
df[['sport', 'dsport']] = df[['sport', 'dsport']].apply(
    pd.to_numeric, errors='coerce'
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype
---  ------            -----
 0   srcip             str
 1   sport             float64
 2   dstip             str
 3   dsport            float64
 4   proto             str
 5   state             str
 6   dur               float64
 7   sbytes            int64
 8   dbytes            int64
 9   sttl              int64
 10  dttl              int64
 11  sloss             int64
 12  dloss             int64
 13  service           str
 14  Sload             float64
 15  Dload             float64
 16  Spkts             int64
 17  Dpkts             int64
 18  swin              int64
 19  dwin              int64
 20  stcpb             int64
 21  dtcpb             int64
 22  smeansz           int64
 23  dmeansz           int64
 24  trans_depth       int64
 25  res_bdy_len       int64
 26  Sjit              float64
 27  Djit              float64
 28  Stime             int64
 29  Ltime             int64
 30  Sintpkt           float64
 31  Dintpkt           float64
 32  tcprtt            float64
 33  synack            float64
 34  ackdat            float64
 35  is_sm_ips_ports   int64
 36  ct_state_ttl      int64
 37  ct_flw_http_mthd  float64
 38  is_ftp_login      float64
 39  ct_ftp_cmd        str
 40  ct_srv_src        int64
 41  ct_srv_dst        int64
 42  ct_dst_ltm        int64
 43  ct_src_ ltm       int64
 44  ct_src_dport_ltm  int64
 45  ct_dst_sport_ltm  int64
 46  ct_dst_src_ltm    int64
 47  attack_cat        str
 48  Label             int64
dtypes: float64(14), int64(28), str(7)
memory usage: 949.6 MB

### 2. Finding abnormal values

In [21]:
df['ct_ftp_cmd'].value_counts()

ct_ftp_cmd
     1429879
0    1066498
1      40077
2       1264
4        960
3        729
6        332
5        290
8         18
Name: count, dtype: int64

In [22]:
df['service'].value_counts()

service
-           1246397
dns          781668
http         206273
ftp-data     125783
smtp          81645
ftp           49090
ssh           47160
pop3           1533
dhcp            172
ssl             142
snmp            113
radius           40
irc              31
Name: count, dtype: int64

In [28]:
df['attack_cat'].value_counts()

attack_cat
Normal              2218764
Generic              215481
Exploits              44525
 Fuzzers              19195
DoS                   16353
 Reconnaissance       12228
 Fuzzers               5051
Analysis               2677
Backdoor               1795
Reconnaissance         1759
 Shellcode             1288
Backdoors               534
Shellcode               223
Worms                   174
Name: count, dtype: int64

### 3. Handling abnormal values

In [35]:
df['service']=df['service'].replace(['-'], pd.NA)
df['service']=df['service'].fillna('unknown')

df['ct_ftp_cmd'] = df['ct_ftp_cmd'].replace([' '], pd.NA)
df['ct_ftp_cmd'] = df['ct_ftp_cmd'].fillna(0)

df['attack_cat'] = df['attack_cat'].fillna('Normal')
df['attack_cat'] = df['attack_cat'].str.strip()
df["attack_cat"] = df["attack_cat"].replace({
    "Backdoors": "Backdoor"
})

print(df[['service','ct_ftp_cmd','attack_cat']].sample(25),"\n")
df['attack_cat'].value_counts()

          service ct_ftp_cmd attack_cat
1798114       dns          0     Normal
47120         dns          0     Normal
1973180       dns          0    Generic
283460    unknown          0     Normal
2248984       dns          0     Normal
558788       http          0     Normal
1966520       dns          0    Generic
2130925      http          0     Normal
2243971       dns          0     Normal
653580   ftp-data          0     Normal
761807    unknown          0     Normal
278461    unknown          0     Normal
2164292   unknown          0     Normal
1365156       dns          0     Normal
2161876       dns          0     Normal
1190370       dns          0     Normal
1685757       dns          0     Normal
500325    unknown          0     Normal
279636    unknown          0     Normal
657744    unknown          0     Normal
1968046      http          0     Normal
2255566   unknown          0     Normal
966834    unknown          0     Normal
305357       http          0     Normal
2314150      http          0     Normal

attack_cat
Normal            2218764
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoor             2329
Shellcode            1511
Worms                 174
Name: count, dtype: int64

### 4. Dropping unnecessary features

In [36]:
data = df.copy()

data = data.drop(['srcip','dstip','dloss','sloss'],axis=1)
data.sample(10)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1440768,1043.0,53.0,udp,INT,0.000010,114,0,254,0,dns,4.560000e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424231942,1424231942,0.010000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,0,27,27,25,25,25,25,27,Generic,1
1359968,63537.0,53.0,udp,CON,0.001195,130,162,31,29,dns,4.351464e+05,5.422594e+05,2,2,0,0,0,0,65,81,0,0,0.000000,0.000000,1424230352,1424230352,0.009000,0.008000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,3,1,1,9,2,1,1,Normal,0
1251968,24384.0,20523.0,tcp,FIN,0.018565,2750,27620,31,29,unknown,1.158309e+06,1.164342e+07,44,46,255,255,790713013,2936375322,63,600,0,0,27.865760,25.926995,1424226167,1424226167,0.424047,0.400467,0.000667,0.000535,0.000132,0,0,NaN,NaN,0,6,14,6,3,1,1,2,Normal,0
1121017,55288.0,55539.0,tcp,FIN,0.024599,3614,50036,31,29,unknown,1.155819e+06,1.601008e+07,60,62,255,255,3548634691,1403566213,60,807,0,0,22.124006,21.069836,1424222345,1424222345,0.418534,0.398967,0.000780,0.000652,0.000128,0,0,NaN,NaN,0,5,4,2,3,1,1,1,Normal,0
2092303,35639.0,5190.0,tcp,FIN,0.016262,1036,2366,31,29,unknown,4.673472e+05,1.080802e+06,12,14,255,255,3252857422,1103564184,86,169,0,0,127.973494,3.331630,1424249711,1424249711,1.447273,1.306000,0.000727,0.000581,0.000146,0,0,NaN,NaN,0,5,8,1,2,1,1,1,Normal,0
775756,25059.0,5190.0,tcp,FIN,0.005924,1920,4312,31,29,unknown,2.475354e+06,5.581364e+06,22,24,255,255,273959878,2423824657,87,180,0,0,16.429815,13.489067,1421959270,1421959270,0.264667,0.233739,0.000669,0.000547,0.000122,0,0,0.0,0.0,0,5,2,1,3,1,1,1,Normal,0
1795198,34575.0,21.0,tcp,FIN,4.465836,2934,3742,31,29,ftp,5.155585e+03,6.579731e+03,52,54,255,255,1750250660,2044018808,56,69,0,0,6626.711407,199.461219,1424241387,1424241392,87.558683,84.250359,0.000684,0.000557,0.000127,0,0,NaN,1.0,1,1,1,1,1,1,1,4,Normal,0
2401773,0.0,0.0,unas,INT,0.000009,200,0,254,0,unknown,8.888889e+07,0.000000e+00,2,0,0,0,0,0,100,0,0,0,0.000000,0.000000,1424258885,1424258885,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,0,6,6,2,3,2,2,6,Backdoor,1
2059805,11292.0,80.0,tcp,RST,0.081830,258,86,254,60,unknown,2.101919e+04,4.203837e+03,6,2,255,255,2335862533,1092822598,43,43,0,0,1040.463711,0.000000,1424248389,1424248389,16.366000,0.008000,0.073051,0.055426,0.017625,0,0,NaN,NaN,0,23,23,9,9,9,1,23,Normal,0
1065766,20938.0,6881.0,tcp,FIN,0.027094,1540,1644,31,29,unknown,4.263675e+05,4.585517e+05,16,18,255,255,3048066194,927622089,96,91,0,0,109.646193,2.755523,1421971751,1421971751,1.784867,1.566706,0.000589,0.000457,0.000132,0,0,0.0,0.0,0,6,3,2,4,3,1,2,Normal,0

### 5. Sample of the cleaned data

In [37]:
data.sample(15)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1492564,22405.0,80.0,tcp,FIN,1.090992,1580,10168,31,29,http,1.062519e+04,7.042398e+04,12,18,255,255,679268717,680303678,132,565,1,0,10197.788880,8213.224778,1424232963,1424232964,99.150453,64.141708,0.000722,0.000577,0.000145,0,0,1.0,NaN,0,1,1,5,6,1,1,2,Normal,0
1417332,11879.0,53.0,udp,CON,0.000995,146,178,31,29,dns,5.869347e+05,7.155779e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424231518,1424231518,0.001000,0.009000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,2,4,4,2,1,1,1,Normal,0
1000296,25546.0,20251.0,tcp,FIN,0.015631,2766,28558,31,29,unknown,1.383917e+06,1.429877e+07,44,46,255,255,878958689,879274056,63,621,0,0,19.882950,18.557385,1421969121,1421969121,0.355721,0.334000,0.000726,0.000590,0.000136,0,0,0.0,0.0,0,5,6,1,2,1,1,1,Normal,0
714577,42626.0,5190.0,tcp,FIN,0.006219,2152,2410,31,29,unknown,2.662808e+06,2.981830e+06,26,26,255,255,1403981350,3549675877,83,93,0,0,14.063985,0.000000,1421956541,1421956541,0.244250,0.225200,0.000721,0.000578,0.000143,0,0,0.0,0.0,0,15,11,6,7,2,1,4,Normal,0
603808,12390.0,53.0,udp,CON,0.001023,146,178,31,29,dns,5.708700e+05,6.959922e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421950801,1421950801,0.007000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,4,1,2,5,2,1,1,Normal,0
392405,18036.0,80.0,tcp,FIN,1.509855,1580,10168,31,29,http,7.677558e+03,5.088700e+04,12,18,255,255,2571419720,434295184,132,565,1,3924,11572.182290,9314.740171,1421943854,1421943856,137.145818,88.783824,0.000708,0.000526,0.000182,0,0,1.0,0.0,0,4,1,1,4,1,1,1,Normal,0
1374803,47439.0,53.0,udp,INT,0.000009,264,0,60,0,dns,1.173333e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424230527,1424230527,0.009000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,35,35,33,33,33,16,35,Normal,0
495499,30244.0,56523.0,tcp,FIN,0.006388,4144,2456,31,29,unknown,4.901690e+06,2.905448e+06,18,18,255,255,898166894,901260777,230,136,0,0,17.969678,0.467364,1421945963,1421945963,0.355647,0.347353,0.000603,0.000478,0.000125,0,0,0.0,0.0,0,4,6,4,4,1,1,3,Normal,0
378922,36547.0,25.0,tcp,FIN,0.083880,37402,3276,31,29,smtp,3.498617e+06,3.047210e+05,52,40,255,255,340835462,2487388814,719,82,0,0,214.248793,7.108833,1421943264,1421943264,1.636627,2.136487,0.000690,0.000553,0.000137,0,0,0.0,0.0,0,1,1,2,3,1,1,1,Normal,0
2144691,1043.0,53.0,udp,INT,0.000010,264,0,60,0,dns,1.056000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424251657,1424251657,0.010000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,21,21,18,18,18,18,21,Normal,0
2403312,1628.0,514.0,udp,INT,0.000010,1606,0,254,0,unknown,6.424000e+08,0.000000e+00,2,0,0,0,0,0,803,0,0,0,0.000000,0.000000,1424258913,1424258913,0.010000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,0,11,3,2,5,2,1,3,Normal,0
1502171,1043.0,53.0,udp,INT,0.000007,264,0,60,0,dns,1.508571e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424233188,1424233188,0.007000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,22,22,22,22,22,9,22,Normal,0
776968,43933.0,25.0,tcp,FIN,0.053776,37866,3380,31,29,smtp,5.528860e+06,4.909253e+05,54,42,255,255,401707370,2552381843,701,80,0,0,59.529635,2.668974,1421959324,1421959324,1.008094,1.298610,0.000657,0.000526,0.000131,0,0,0.0,0.0,0,3,1,6,8,2,1,2,Normal,0
1478310,4185.0,46676.0,tcp,FIN,0.004852,3704,2456,31,29,unknown,5.769167e+06,3.825226e+06,18,18,255,255,3517090512,1370700441,206,136,0,0,13.191673,0.335971,1424232578,1424232578,0.266588,0.252294,0.000717,0.000559,0.000158,0,0,NaN,NaN,0,3,7,4,4,1,1,4,Normal,0
2350473,43956.0,4115.0,tcp,FIN,0.028827,4014,56418,31,29,unknown,1.097582e+06,1.543359e+07,68,70,255,255,2001277346,4160747466,59,806,0,0,0.000000,22.916895,1424256935,1424256935,0.438708,0.413776,0.001263,0.001101,0.000162,0,0,NaN,NaN,0,5,4,1,3,1,1,2,Normal,0

### 6. Save the dataset

In [38]:
data.to_csv(r"C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\processed-data\clean-data.csv", index=False)