## Data Preprocessing

### 1. Load the libraries

In [10]:
import pandas as pd

### 2. Load the dataset

In [2]:
df = pd.read_csv(r'/Detector/data/raw/UNSW-NB15.csv', low_memory=False)
pd.set_option('display.max_columns', None)
df.sample(15)

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1070321,59.166.0.1,4075,149.171.126.0,29877,tcp,FIN,0.074026,3598,46456,31,29,7,24,-,3.824602e+05,4.939562e+06,60,62,255,255,1426749469,1427107029,60,749,0,0,75.734985,74.477938,1421971920,1421971921,1.248458,1.202246,0.000840,0.000678,0.000162,0,0,0.0,0.0,0,5,9,5,3,1,1,1,NaN,0
796968,59.166.0.0,40888,149.171.126.5,25,tcp,FIN,0.042993,37322,3380,31,29,18,8,smtp,6.811341e+06,6.140534e+05,52,42,255,255,35695935,38311406,718,80,0,0,55.927218,2.436786,1421960196,1421960196,0.836196,1.037219,0.000615,0.000466,0.000149,0,0,0.0,0.0,0,1,1,3,3,1,1,1,NaN,0
2111782,59.166.0.8,54145,149.171.126.5,80,tcp,FIN,12.998958,18786,1087890,31,29,2,370,http,1.152892e+04,6.686271e+05,352,746,255,255,3827169621,3840191417,53,1458,1,524288,2544.449321,1667.132123,1424250478,1424250491,37.033176,17.447535,0.000666,0.000541,0.000125,0,0,1.0,NaN,,2,2,3,3,1,1,2,NaN,0
752542,59.166.0.6,44911,149.171.126.9,5190,tcp,FIN,0.243479,3002,21714,31,29,8,12,-,9.604114e+04,6.964708e+05,38,42,255,255,204478315,2350149539,79,517,0,0,810.277384,777.623790,1421958289,1421958289,6.570865,5.924317,0.000700,0.000576,0.000124,0,0,0.0,0.0,0,9,7,2,7,1,1,1,NaN,0
1286043,59.166.0.7,25058,149.171.126.2,22570,tcp,FIN,0.077849,4550,67380,31,29,7,33,-,4.616116e+05,6.837647e+06,78,80,255,255,2405354421,2409946288,58,842,0,0,63.783855,63.073676,1424227644,1424227644,1.007052,0.990859,0.000705,0.000553,0.000152,0,0,NaN,NaN,,7,14,4,4,1,1,1,NaN,0
1314102,59.166.0.6,12489,149.171.126.9,44158,tcp,FIN,0.009856,2334,16290,31,29,7,12,-,1.842532e+06,1.287500e+07,36,38,255,255,2486772723,337493613,65,429,0,0,16.702148,14.479042,1424228678,1424228678,0.275353,0.256778,0.000747,0.000603,0.000144,0,0,NaN,NaN,,9,10,2,9,1,1,2,NaN,0
1128503,59.166.0.2,8385,149.171.126.9,45403,tcp,FIN,0.174714,3598,48710,31,29,7,24,-,1.620477e+05,2.194444e+06,60,62,255,255,2367492991,2371986069,60,786,0,0,168.990089,166.079756,1424222640,1424222640,2.954797,2.853803,0.000763,0.000623,0.000140,0,0,NaN,NaN,,5,1,5,2,1,1,1,NaN,0
1574668,59.166.0.9,33517,149.171.126.2,8586,tcp,FIN,0.002751,320,1890,31,29,1,2,ftp-data,7.764449e+05,4.809888e+06,6,8,255,255,3843521979,1701822090,53,236,0,0,27.298536,0.517341,1424235452,1424235452,0.488600,0.325000,0.000598,0.000474,0.000124,0,0,NaN,NaN,,4,3,6,5,1,1,4,NaN,0
1763855,59.166.0.9,60947,149.171.126.1,22026,tcp,FIN,0.008953,2230,13358,31,29,7,11,-,1.934547e+06,1.160460e+07,34,36,255,255,2383565955,2383880638,66,371,0,0,15.236627,14.066504,1424240386,1424240386,0.261848,0.235571,0.000819,0.000700,0.000119,0,0,NaN,NaN,,10,3,2,4,1,1,2,NaN,0
1085782,59.166.0.5,23484,149.171.126.1,21307,tcp,FIN,0.023948,2854,30744,31,29,7,17,-,9.326874e+05,1.005646e+07,46,48,255,255,4110505320,1992813207,62,641,0,0,0.000000,28.395845,1421972659,1421972659,0.524889,0.499021,0.000629,0.000491,0.000138,0,0,0.0,0.0,0,7,3,2,2,1,1,1,NaN,0
791331,59.166.0.0,46230,149.171.126.5,53,udp,CON,0.001033,132,164,31,29,0,0,dns,5.111327e+05,6.350436e+05,2,2,0,0,0,0,66,82,0,0,0.000000,0.000000,1421959945,1421959945,0.011000,0.009000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,1,4,7,1,1,1,NaN,0
961325,59.166.0.5,13649,149.171.126.9,5190,tcp,FIN,0.006110,2054,2478,31,29,6,6,-,2.567594e+06,3.109656e+06,22,24,255,255,2978556404,2978849260,93,103,0,0,15.563412,14.196579,1421967306,1421967306,0.251476,0.241217,0.000697,0.000561,0.000136,0,0,0.0,0.0,0,6,7,1,5,1,1,1,NaN,0
1270664,175.45.176.0,37202,149.171.126.14,80,tcp,FIN,0.184467,1200,268,254,252,2,1,http,4.683764e+04,9.714475e+03,10,6,255,255,2185940565,2361381472,120,45,1,0,1039.478816,62.610836,1424227007,1424227007,19.349000,35.606801,0.051744,0.006414,0.045330,0,1,1.0,NaN,,1,1,1,2,1,1,1,Reconnaissance,1
619184,59.166.0.9,55906,149.171.126.0,53,udp,CON,0.001058,146,178,31,29,0,0,dns,5.519849e+05,6.729679e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421951467,1421951467,0.010000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,4,3,4,1,1,1,NaN,0
2533226,59.166.0.8,1795,149.171.126.9,53,udp,CON,0.000958,130,162,31,29,0,0,dns,5.427975e+05,6.764092e+05,2,2,0,0,0,0,65,81,0,0,0.000000,0.000000,1424261923,1424261923,0.002000,0.005000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,1,2,1,1,1,1,1,NaN,0

### 3. Datatypes of the features

In [4]:
df[['sport', 'dsport']] = df[['sport', 'dsport']].apply(
    pd.to_numeric, errors='coerce'
).fillna(0)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype
---  ------            -----
 0   srcip             str
 1   sport             float64
 2   dstip             str
 3   dsport            float64
 4   proto             str
 5   state             str
 6   dur               float64
 7   sbytes            int64
 8   dbytes            int64
 9   sttl              int64
 10  dttl              int64
 11  sloss             int64
 12  dloss             int64
 13  service           str
 14  Sload             float64
 15  Dload             float64
 16  Spkts             int64
 17  Dpkts             int64
 18  swin              int64
 19  dwin              int64
 20  stcpb             int64
 21  dtcpb             int64
 22  smeansz           int64
 23  dmeansz           int64
 24  trans_depth       int64
 25  res_bdy_len       int64
 26  Sjit              float64
 27  Djit              float64
 28  Stime             int64
 29  Ltime             int64
 30  Sintpkt           float64
 31  Dintpkt           float64
 32  tcprtt            float64
 33  synack            float64
 34  ackdat            float64
 35  is_sm_ips_ports   int64
 36  ct_state_ttl      int64
 37  ct_flw_http_mthd  float64
 38  is_ftp_login      float64
 39  ct_ftp_cmd        object
 40  ct_srv_src        int64
 41  ct_srv_dst        int64
 42  ct_dst_ltm        int64
 43  ct_src_ ltm       int64
 44  ct_src_dport_ltm  int64
 45  ct_dst_sport_ltm  int64
 46  ct_dst_src_ltm    int64
 47  attack_cat        str
 48  Label             int64
dtypes: float64(14), int64(28), object(1), str(6)
memory usage: 949.6+ MB

### 2. Find null features

In [5]:
df.isnull().sum()[df.isnull().sum() > 0]

ct_flw_http_mthd    1348145
is_ftp_login        1429879
attack_cat          2218764
dtype: int64

In [8]:
df['ct_ftp_cmd'].value_counts()

ct_ftp_cmd
     1429879
0    1066498
1      40077
2       1264
4        960
3        729
6        332
5        290
8         18
Name: count, dtype: int64

### 3. Handling NULL values

In [3]:
df['service']=df['service'].replace(['-'], pd.NA)
df['service']=df['service'].fillna('unknown')

df['ct_ftp_cmd'] = df['ct_ftp_cmd'].replace([' '], pd.NA)
df['ct_ftp_cmd'] = df['ct_ftp_cmd'].fillna(0)

df[['ct_flw_http_mthd', 'is_ftp_login']]=df[['ct_flw_http_mthd', 'is_ftp_login']].fillna(0)

print(df[['service','ct_ftp_cmd','ct_flw_http_mthd', 'is_ftp_login']].sample(25))

          service ct_ftp_cmd  ct_flw_http_mthd  is_ftp_login
129184    unknown          0               0.0           0.0
2433228       dns          0               0.0           0.0
2522712  ftp-data          0               0.0           0.0
2161624       dns          0               0.0           0.0
2351524  ftp-data          0               0.0           0.0
1036606   unknown          0               0.0           0.0
2529184       dns          0               0.0           0.0
1958699       dns          0               0.0           0.0
1087449   unknown          0               0.0           0.0
2069209  ftp-data          0               0.0           0.0
981417       http          0               1.0           0.0
1541393       dns          0               0.0           0.0
1033448   unknown          0               0.0           0.0
947718    unknown          0               0.0           0.0
1173890   unknown          0               0.0           0.0
1550296   unknown          0               0.0           0.0
972652       http          0               1.0           0.0
258481   ftp-data          0               0.0           0.0
2484334       dns          0               0.0           0.0
2270476       dns          0               0.0           0.0
1181774       dns          0               0.0           0.0
1455706       dns          0               0.0           0.0
97784     unknown          0               0.0           0.0
2305489   unknown          0               0.0           0.0
653064    unknown          0               0.0           0.0

### 4. Dropping unnecessary features

In [6]:
data = df.copy()

data = data.drop(['srcip','dstip','dloss','sloss','attack_cat'],axis=1)
data.sample(10)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,Label
1030568,47929.0,5190.0,tcp,FIN,0.139242,2062,2424,31,29,unknown,1.135864e+05,1.339251e+05,24,26,255,255,2127166039,4277075361,86,93,0,0,432.832664,0.000000,1421970372,1421970372,6.039522,5.543800,0.000768,0.000613,0.000155,0,0,0.0,0.0,0,4,12,4,3,1,1,1,0
1875636,0.0,0.0,unas,INT,0.000005,200,0,254,0,unknown,1.600000e+08,0.000000e+00,2,0,0,0,0,0,100,0,0,0,0.000000,0.000000,1424244439,1424244439,0.005000,0.000000,0.000000,0.000000,0.000000,0,2,0.0,0.0,0,9,9,4,4,3,3,12,1
1439802,47439.0,53.0,udp,INT,0.000009,264,0,60,0,dns,1.173333e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424231928,1424231928,0.009000,0.000000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,43,43,21,21,21,21,43,0
1867262,48781.0,80.0,tcp,FIN,1.005946,1580,10168,31,29,http,1.152348e+04,7.637785e+04,12,18,255,255,2498202745,2499235763,132,565,1,0,9528.113445,7672.514090,1424244312,1424244313,91.416727,59.141881,0.000653,0.000530,0.000123,0,0,1.0,0.0,0,3,2,3,2,1,1,2,0
481041,60091.0,20364.0,tcp,FIN,0.046475,3286,38430,31,29,unknown,5.553093e+05,6.487961e+06,54,52,255,255,2076332176,2094271067,61,739,0,0,59.697981,60.551399,1421945564,1421945564,0.870981,0.901000,0.000662,0.000518,0.000144,0,0,0.0,0.0,0,12,24,13,12,3,3,3,0
1860006,15280.0,49912.0,tcp,FIN,0.126327,320,1864,31,29,ftp-data,1.690850e+04,1.032875e+05,6,8,255,255,4225087093,297007630,53,233,0,0,1771.408636,43.701113,1424244004,1424244004,25.203200,17.964285,0.000735,0.000576,0.000159,0,0,0.0,0.0,0,3,1,1,4,1,1,1,0
670260,36507.0,14960.0,tcp,FIN,0.041295,2542,21294,31,29,unknown,4.802518e+05,4.027025e+06,40,42,255,255,123681908,129340333,64,507,0,0,0.000000,64.535708,1421953736,1421953736,1.049590,0.995366,0.000613,0.000481,0.000132,0,0,0.0,0.0,0,7,6,2,3,1,1,1,0
320159,62580.0,18863.0,tcp,FIN,0.011963,2334,16734,31,29,unknown,1.518014e+06,1.089626e+07,36,38,255,255,990854463,3140757448,65,440,0,0,18.770759,18.507663,1421940534,1421940534,0.332743,0.307000,0.000724,0.000593,0.000131,0,0,0.0,0.0,0,1,6,1,1,1,1,1,0
394483,45216.0,53.0,udp,CON,0.001083,146,178,31,29,dns,5.392429e+05,6.574331e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421943945,1421943945,0.011000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,2,4,4,1,1,2,0
2351994,63210.0,143.0,tcp,FIN,0.235982,904,1364,31,29,unknown,2.874796e+04,4.393555e+04,16,20,255,255,1996507092,4156741265,57,68,0,0,20.712154,19.300100,1424256988,1424256988,15.709866,12.382685,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,6,5,4,6,4,4,4,0

"attack_cat" was removed because the project is divided into two distinct models one that will detect the attack and another will predict the attack category this feature will be added in the 2nd model

### 5. Sample of the cleaned data

In [9]:
data.sample(15)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,Label
2254547,24400.0,22756.0,tcp,FIN,0.014952,2542,23354,31,29,unknown,1.326378e+06,1.219797e+07,40,42,255,255,922636885,3072529477,64,556,0,0,21.075146,20.898473,1424253948,1424253948,0.375231,0.358225,0.000753,0.000614,0.000139,0,0,0.0,0.0,0,6,8,2,3,1,1,3,0
1138433,52759.0,80.0,tcp,FIN,1.004923,1580,10168,31,29,http,1.153521e+04,7.645561e+04,12,18,255,255,1608842140,3755238420,132,565,1,3924,9528.466714,7676.591211,1424223022,1424223023,91.326906,59.082238,0.000650,0.000522,0.000128,0,0,1.0,0.0,0,4,3,2,2,2,1,2,0
1282364,50922.0,80.0,tcp,FIN,1.058995,1684,10168,31,29,http,1.181498e+04,7.255180e+04,14,18,255,255,4188894362,4189850057,120,565,1,3924,8776.191422,7921.630215,1424227504,1424227505,81.435231,66.153252,0.000678,0.000540,0.000138,0,0,1.0,0.0,0,2,2,7,9,1,1,1,0
227591,46646.0,53.0,udp,CON,0.001021,146,178,31,29,dns,5.719882e+05,6.973556e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421936161,1421936161,0.010000,0.003000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,1,4,3,1,1,1,1,0
2383038,31776.0,54587.0,tcp,FIN,0.140358,320,1948,31,29,ftp-data,1.521823e+04,9.718007e+04,6,8,255,255,987559636,3314195336,53,244,0,0,1970.588234,48.604004,1424258308,1424258308,28.010000,19.972715,0.000689,0.000547,0.000142,0,0,0.0,0.0,0,2,2,2,4,1,1,3,0
488172,27167.0,80.0,tcp,FIN,1.005988,1684,10168,31,29,unknown,1.243752e+04,7.637467e+04,14,18,255,255,24208348,2174773357,120,565,1,3924,8765.906719,7676.057564,1421945643,1421945644,77.353692,59.145000,0.000643,0.000519,0.000124,0,0,6.0,0.0,0,12,12,13,11,5,5,5,0
1544167,21993.0,35870.0,tcp,FIN,0.015850,2766,28892,31,29,unknown,1.364795e+06,1.426574e+07,44,46,255,255,3905374583,1760246706,63,628,0,0,0.000000,20.344335,1424234218,1424234218,0.378659,0.348114,0.000651,0.000530,0.000121,0,0,0.0,0.0,0,10,5,4,4,1,1,2,0
691769,24491.0,59051.0,tcp,FIN,0.171192,4408,2664,31,29,unknown,1.966447e+05,1.188373e+05,22,22,255,255,4226144765,4225164066,200,121,0,0,722.194406,21.155754,1421955464,1421955465,8.128857,8.125667,0.000711,0.000546,0.000165,0,0,0.0,0.0,0,8,10,1,1,1,1,1,0
2149005,1043.0,53.0,udp,INT,0.000008,264,0,60,0,dns,1.320000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424251702,1424251702,0.008000,0.000000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,35,35,35,35,35,18,35,0
2177579,46078.0,12319.0,tcp,FIN,0.002945,320,1956,31,29,ftp-data,7.252971e+05,4.650594e+06,6,8,255,255,3417021121,1271332097,53,245,0,0,29.247680,0.571537,1424252263,1424252263,0.525200,0.346000,0.000648,0.000518,0.000130,0,0,0.0,0.0,0,4,1,1,1,1,1,6,0
610688,5337.0,53.0,udp,CON,0.000993,130,162,31,29,dns,5.236657e+05,6.525680e+05,2,2,0,0,0,0,65,81,0,0,0.000000,0.000000,1421951100,1421951100,0.007000,0.029000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,6,5,4,1,1,1,0
2214675,58062.0,54527.0,tcp,FIN,0.305839,4376,2976,31,29,unknown,1.100710e+05,7.507218e+04,26,28,255,255,364013856,2512702099,168,106,0,0,718.315496,18.583799,1424253153,1424253153,12.221080,11.307593,0.000657,0.000530,0.000127,0,0,0.0,0.0,0,5,3,4,3,1,1,3,0
611786,57467.0,53.0,udp,CON,0.001079,146,178,31,29,dns,5.412419e+05,6.598702e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421951146,1421951146,0.011000,0.010000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,3,2,2,1,1,1,0
1888932,47439.0,53.0,udp,INT,0.000033,114,0,254,0,dns,1.381818e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424244670,1424244670,0.033000,0.000000,0.000000,0.000000,0.000000,0,2,0.0,0.0,0,57,57,57,57,57,26,57,1
2538566,1043.0,53.0,udp,INT,0.000007,264,0,60,0,dns,1.508571e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424262040,1424262040,0.007000,0.000000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,31,31,18,18,18,18,31,0

### 5. Save the clean dataset

In [11]:
data.to_csv(r"C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\processed-data\clean-data.csv")