## Data Preprocessing

### 1. Load the libraries

In [18]:
import pandas as pd

### 2. Load the dataset

In [19]:
df = pd.read_csv(r'C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\UNSW-NB15.csv', low_memory=False)
pd.set_option('display.max_columns', None)
df.sample(15)

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1717152,175.45.176.1,47439,149.171.126.18,53,udp,INT,0.000009,114,0,254,0,0,0,dns,5.066666e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424239201,1424239201,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,,39,39,33,33,33,15,39,Generic,1
2054841,59.166.0.6,32800,149.171.126.1,5190,tcp,FIN,0.148440,1244,2574,31,29,4,4,-,6.289410e+04,1.310159e+05,16,18,255,255,693891948,2839612235,78,143,0,0,626.141339,16.203723,1424248203,1424248204,9.858800,8.694471,0.000767,0.000625,0.000142,0,0,NaN,NaN,,3,1,2,3,1,1,1,NaN,0
2322563,59.166.0.2,5938,149.171.126.8,53,udp,CON,0.001008,146,178,31,29,0,0,dns,5.793651e+05,7.063492e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424255862,1424255862,0.004000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,3,4,5,5,2,1,1,NaN,0
2488341,59.166.0.2,26317,149.171.126.4,24540,tcp,FIN,0.055140,4550,72346,31,29,7,33,-,6.517229e+05,1.036518e+07,78,80,255,255,2324193461,192150553,58,904,0,0,43.628672,42.626437,1424260769,1424260769,0.712130,0.700769,0.000602,0.000477,0.000125,0,0,NaN,NaN,,10,1,4,8,1,1,1,NaN,0
2499014,59.166.0.4,26924,149.171.126.4,111,udp,CON,0.284242,568,304,31,29,0,0,-,1.198978e+04,6.417067e+03,4,4,0,0,0,0,142,76,0,0,126.784953,33.886207,1424261005,1424261005,89.659000,23.965666,0.000000,0.000000,0.000000,0,0,NaN,NaN,,4,5,5,3,1,1,4,NaN,0
915858,59.166.0.6,11574,149.171.126.8,9626,tcp,FIN,0.027460,3614,48202,31,29,7,24,-,1.035397e+06,1.382345e+07,60,64,255,255,3078235913,3100015380,60,753,0,0,23.940830,23.261759,1421965223,1421965223,0.466879,0.428127,0.000626,0.000485,0.000141,0,0,0.0,0.0,0,4,8,3,4,1,1,2,NaN,0
2389518,59.166.0.9,19830,149.171.126.6,53,udp,CON,0.001087,146,178,31,29,0,0,dns,5.372585e+05,6.550138e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424258595,1424258595,0.008000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,2,2,4,1,1,1,2,NaN,0
2079675,59.166.0.8,20784,149.171.126.0,80,tcp,FIN,1.039240,1580,10168,31,29,3,5,http,1.115430e+04,7.393095e+04,12,18,255,255,2166311655,2171476986,132,565,1,3924,9561.991236,7699.894020,1424249194,1424249195,94.444000,61.100591,0.000650,0.000526,0.000124,0,0,1.0,NaN,,1,1,1,4,1,1,1,NaN,0
2329406,59.166.0.3,22464,149.171.126.1,47019,udp,CON,0.001560,528,304,31,29,0,0,-,2.030769e+06,1.169231e+06,4,4,0,0,0,0,132,76,0,0,0.558143,0.255501,1424256121,1424256121,0.397667,0.182667,0.000000,0.000000,0.000000,0,0,NaN,NaN,,5,11,5,4,1,1,5,NaN,0
1969653,149.171.126.15,1043,175.45.176.3,53,udp,INT,0.000004,264,0,60,0,0,0,dns,2.640000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424246233,1424246233,0.004000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,22,22,22,22,22,22,22,NaN,0
290463,59.166.0.3,60820,149.171.126.7,111,udp,CON,0.004626,568,304,31,29,0,0,-,7.367056e+05,3.942931e+05,4,4,0,0,0,0,142,76,0,0,1.763289,1.461119,1421939104,1421939104,1.251333,1.036667,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,4,2,1,2,1,1,1,NaN,0
2336706,10.40.182.6,138,10.40.182.255,138,udp,INT,0.000079,503,0,64,0,0,0,-,2.551899e+07,0.000000e+00,2,0,0,0,0,0,252,0,0,0,0.000000,0.000000,1424256414,1424256414,0.079000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,3,3,3,3,3,3,3,NaN,0
1737674,59.166.0.1,9375,149.171.126.8,46000,tcp,FIN,0.261675,4096,2872,31,29,7,7,-,1.204242e+05,8.444062e+04,26,26,255,255,62398259,65808955,158,110,0,0,648.339333,17.529848,1424239666,1424239666,10.454600,10.444520,0.000689,0.000557,0.000132,0,0,NaN,NaN,,5,6,7,4,1,1,4,NaN,0
1086355,59.166.0.0,53547,149.171.126.4,21,tcp,FIN,0.391961,2934,3740,31,29,11,15,ftp,5.874054e+04,7.492582e+04,52,54,255,255,2594830055,2592122662,56,69,0,0,972.513998,37.643258,1421972685,1421972685,7.679216,7.384094,0.000750,0.000593,0.000157,0,0,0.0,1.0,1,1,2,3,3,1,1,2,NaN,0
51743,59.166.0.1,57739,149.171.126.9,53,udp,CON,0.001054,146,178,31,29,0,0,dns,5.540797e+05,6.755218e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421929477,1421929477,0.011000,0.012000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,5,6,2,3,2,1,1,NaN,0

### 3. Datatypes of the features

In [20]:
df[['sport', 'dsport']] = df[['sport', 'dsport']].apply(
    pd.to_numeric, errors='coerce'
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype
---  ------            -----
 0   srcip             str
 1   sport             float64
 2   dstip             str
 3   dsport            float64
 4   proto             str
 5   state             str
 6   dur               float64
 7   sbytes            int64
 8   dbytes            int64
 9   sttl              int64
 10  dttl              int64
 11  sloss             int64
 12  dloss             int64
 13  service           str
 14  Sload             float64
 15  Dload             float64
 16  Spkts             int64
 17  Dpkts             int64
 18  swin              int64
 19  dwin              int64
 20  stcpb             int64
 21  dtcpb             int64
 22  smeansz           int64
 23  dmeansz           int64
 24  trans_depth       int64
 25  res_bdy_len       int64
 26  Sjit              float64
 27  Djit              float64
 28  Stime             int64
 29  Ltime             int64
 30  Sintpkt           float64
 31  Dintpkt           float64
 32  tcprtt            float64
 33  synack            float64
 34  ackdat            float64
 35  is_sm_ips_ports   int64
 36  ct_state_ttl      int64
 37  ct_flw_http_mthd  float64
 38  is_ftp_login      float64
 39  ct_ftp_cmd        str
 40  ct_srv_src        int64
 41  ct_srv_dst        int64
 42  ct_dst_ltm        int64
 43  ct_src_ ltm       int64
 44  ct_src_dport_ltm  int64
 45  ct_dst_sport_ltm  int64
 46  ct_dst_src_ltm    int64
 47  attack_cat        str
 48  Label             int64
dtypes: float64(14), int64(28), str(7)
memory usage: 949.6 MB

### 2. Finding missing values

In [21]:
df['ct_ftp_cmd'].value_counts()

ct_ftp_cmd
     1429879
0    1066498
1      40077
2       1264
4        960
3        729
6        332
5        290
8         18
Name: count, dtype: int64

In [22]:
df['service'].value_counts()

service
-           1246397
dns          781668
http         206273
ftp-data     125783
smtp          81645
ftp           49090
ssh           47160
pop3           1533
dhcp            172
ssl             142
snmp            113
radius           40
irc              31
Name: count, dtype: int64

### 3. Handling missing values

In [23]:
df['service']=df['service'].replace(['-'], pd.NA)
df['service']=df['service'].fillna('unknown')

df['ct_ftp_cmd'] = df['ct_ftp_cmd'].replace([' '], pd.NA)
df['ct_ftp_cmd'] = df['ct_ftp_cmd'].fillna(0)

print(df[['service','ct_ftp_cmd','ct_flw_http_mthd', 'is_ftp_login']].sample(25))

          service ct_ftp_cmd  ct_flw_http_mthd  is_ftp_login
1628526   unknown          0               NaN           NaN
146740    unknown          0               0.0           0.0
1945653       dns          0               NaN           NaN
635346    unknown          0               0.0           0.0
1541751      smtp          0               NaN           NaN
35198     unknown          0               0.0           0.0
875925       smtp          0               0.0           0.0
1464137       dns          0               NaN           NaN
1279881   unknown          0               NaN           NaN
2343496       dns          0               NaN           NaN
712921   ftp-data          0               0.0           0.0
1242751   unknown          0               NaN           NaN
1198615      http          0               1.0           NaN
1883960       dns          0               NaN           NaN
2176240      smtp          0               NaN           NaN
370202       smtp          0               0.0           0.0
2041557       dns          0               NaN           NaN
807563    unknown          0               0.0           0.0
1277524   unknown          0               NaN           NaN
2266806       dns          0               NaN           NaN
1727322   unknown          0               NaN           NaN
1481095       dns          0               NaN           NaN
2400404       dns          0               NaN           NaN
420265        dns          0               0.0           0.0
676047        ssh          0               0.0           0.0

### 4. Dropping unnecessary features

In [24]:
data = df.copy()

data = data.drop(['srcip','dstip','dloss','sloss'],axis=1)
data.sample(10)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
766091,55986.0,5190.0,tcp,FIN,0.004333,1036,2262,31,29,unknown,1.753981e+06,3.829218e+06,12,12,255,255,224514609,224801292,86,189,0,0,17.370523,0.408284,1421958844,1421958844,0.348818,0.341364,0.000715,0.000566,0.000149,0,0,0.0,0.0,0,8,3,2,3,2,1,1,NaN,0
901916,19420.0,80.0,tcp,FIN,2.301971,1684,10168,31,29,http,5.435342e+03,3.337662e+04,14,18,255,255,4018783562,1903820099,120,565,1,3924,14082.768790,12326.689210,1421964620,1421964622,177.048149,135.378941,0.000656,0.000525,0.000131,0,0,1.0,0.0,0,2,3,1,5,1,1,1,NaN,0
347065,40437.0,54367.0,udp,CON,0.001744,544,304,31,29,unknown,1.871560e+06,1.045872e+06,4,4,0,0,0,0,136,76,0,0,0.647710,0.288503,1421941782,1421941782,0.463000,0.208000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,11,7,3,5,1,1,3,NaN,0
1515489,54233.0,143.0,tcp,FIN,4.449940,7820,15196,31,29,unknown,1.394356e+04,2.710329e+04,122,126,255,255,494270972,2749157644,64,121,0,0,2269.187612,2228.739350,1424233511,1424233515,37.080049,35.882927,0.000574,0.000454,0.000120,0,0,NaN,NaN,0,7,3,1,4,1,1,1,NaN,0
2151727,60423.0,53.0,udp,CON,0.000947,130,162,31,29,dns,5.491024e+05,6.842661e+05,2,2,0,0,0,0,65,81,0,0,0.000000,0.000000,1424251728,1424251728,0.001000,0.009000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,1,1,1,2,1,1,6,NaN,0
2126269,32661.0,6881.0,tcp,FIN,0.018101,1540,1644,31,29,unknown,6.381968e+05,6.863709e+05,16,18,255,255,2691529318,546929864,96,91,0,0,72.331720,2.046203,1424251059,1424251059,1.186667,1.038000,0.000563,0.000452,0.000111,0,0,NaN,NaN,0,18,9,5,10,5,1,7,NaN,0
1917731,1231.0,62636.0,udp,CON,0.157048,536,304,31,29,unknown,2.047782e+04,1.161428e+04,4,4,0,0,0,0,134,76,0,0,52.798957,24.515393,1424245359,1424245359,37.343000,17.338000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,9,10,2,6,1,1,3,NaN,0
1628279,2488.0,53.0,udp,CON,0.001044,130,162,31,29,dns,4.980843e+05,6.206896e+05,2,2,0,0,0,0,65,81,0,0,0.000000,0.000000,1424237431,1424237431,0.009000,0.029000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,2,2,5,4,1,1,1,NaN,0
559796,28132.0,80.0,tcp,FIN,0.038110,1032,824,31,29,http,1.895565e+05,1.557596e+05,8,10,255,255,611116707,2760103518,129,82,1,83,303.214861,7.996323,1421948798,1421948798,5.392428,3.900333,0.003190,0.003004,0.000186,0,0,1.0,0.0,0,1,1,2,3,1,1,1,NaN,0
769501,22923.0,21495.0,tcp,FIN,0.006003,3680,2456,31,29,unknown,4.632350e+06,3.091788e+06,18,18,255,255,4134753228,4137976679,204,136,0,0,17.346812,0.448673,1421958990,1421958990,0.334235,0.323647,0.000632,0.000496,0.000136,0,0,0.0,0.0,0,11,11,5,7,1,1,3,NaN,0

### 5. Sample of the cleaned data

In [25]:
data.sample(15)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
2468191,47439.0,53.0,udp,INT,0.000004,264,0,60,0,dns,2.640000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424260376,1424260376,0.004000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,37,37,19,19,19,19,37,NaN,0
1633244,47439.0,53.0,udp,INT,0.000010,264,0,60,0,dns,1.056000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424237543,1424237543,0.010000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,35,35,33,33,33,21,35,NaN,0
192692,30537.0,22.0,tcp,FIN,0.012715,5928,8010,31,29,unknown,3.669996e+06,4.952890e+06,62,58,255,255,3978783186,1829439717,96,138,0,0,14.470895,14.810834,1421934701,1421934701,0.211917,0.212053,0.000633,0.000499,0.000134,0,0,0.0,0.0,0,7,15,7,2,1,1,2,NaN,0
2116939,25591.0,1397.0,tcp,FIN,0.004843,424,8824,31,29,ftp-data,6.128433e+05,1.336197e+07,8,12,255,255,70311636,2226756312,53,735,0,0,41.151946,21.197831,1424250701,1424250701,0.646000,0.396091,0.000598,0.000483,0.000115,0,0,NaN,NaN,0,3,3,5,5,1,1,5,NaN,0
2161669,1043.0,53.0,udp,INT,0.000009,264,0,60,0,dns,1.173333e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424251907,1424251907,0.009000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,36,36,23,23,23,23,36,NaN,0
643947,50935.0,29508.0,udp,CON,0.068128,520,304,31,29,unknown,4.579615e+04,2.677313e+04,4,4,0,0,0,0,130,76,0,0,24.968176,26.385453,1421952620,1421952620,17.663666,18.663334,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,3,6,8,2,1,1,2,NaN,0
1852859,23684.0,62816.0,tcp,FIN,0.059659,3494,42510,31,29,unknown,4.604838e+05,5.602240e+06,58,58,255,255,4017901613,4013991651,60,733,0,0,68.936785,1.908052,1424243703,1424243703,1.078600,1.036281,0.000722,0.000582,0.000140,0,0,NaN,NaN,0,3,5,1,1,1,1,2,NaN,0
1228942,47439.0,53.0,udp,INT,0.000005,264,0,60,0,dns,2.112000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424225381,1424225381,0.005000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,13,13,8,8,8,8,13,NaN,0
983107,22983.0,111.0,udp,CON,0.004676,568,320,31,29,unknown,7.288280e+05,4.106073e+05,4,4,0,0,0,0,142,80,0,0,1.726990,1.501188,1421968314,1421968314,1.227667,1.068000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,7,6,6,4,1,1,3,NaN,0
2110410,47685.0,4291.0,tcp,FIN,0.012635,2646,23838,31,29,unknown,1.635457e+06,1.475077e+07,42,44,255,255,3569481988,1424414945,63,542,0,0,19.552193,16.759393,1424250438,1424250438,0.315000,0.286667,0.000709,0.000586,0.000123,0,0,NaN,NaN,0,8,4,1,1,1,1,2,NaN,0
1560130,55407.0,53.0,udp,CON,0.001026,146,178,31,29,dns,5.692008e+05,6.939571e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424234874,1424234874,0.009000,0.002000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,3,2,3,3,2,1,1,NaN,0
401652,56544.0,53.0,udp,CON,0.001092,146,178,31,29,dns,5.347985e+05,6.520146e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421944279,1421944279,0.011000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,2,3,2,2,1,1,NaN,0
782796,34215.0,40396.0,tcp,FIN,0.021254,2558,23470,31,29,unknown,9.391174e+05,8.624071e+06,40,42,255,255,2823238486,2843295231,64,559,0,0,0.000000,34.271595,1421959575,1421959575,0.536538,0.519475,0.000619,0.000471,0.000148,0,0,0.0,0.0,0,13,8,4,3,1,1,1,NaN,0
1333821,22890.0,20894.0,tcp,FIN,0.235036,8928,320,31,29,ftp-data,2.822036e+05,9.087970e+03,14,6,255,255,3645985798,442072083,638,53,0,0,1587.578602,71.274469,1424229427,1424229427,18.079693,46.877602,0.000645,0.000519,0.000126,0,0,NaN,NaN,0,1,1,5,4,1,1,3,NaN,0
1547928,11422.0,53.0,udp,CON,0.001024,146,178,31,29,dns,5.703125e+05,6.953125e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424234378,1424234378,0.004000,0.002000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,1,4,4,3,1,1,2,NaN,0

### 6. Save the dataset

In [26]:
data.to_csv(r"C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\processed-data\clean-data.csv", index=False)