## Data Preprocessing

### 1. Load the libraries

In [5]:
import pandas as pd

### 2. Load the dataset

In [16]:
df = pd.read_csv(r'C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\UNSW-NB15.csv', low_memory=False)
pd.set_option('display.max_columns', None)
df.sample(15)

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
439786,59.166.0.3,32716,149.171.126.2,80,tcp,FIN,1.371236,1684,10168,31,29,3,5,-,9.124615e+03,5.603120e+04,14,18,255,255,1089337736,1092339145,120,565,2,192,10526.060400,9253.644628,1421945126,1421945127,105.452228,80.596118,0.001225,0.001093,0.000132,0,0,6.0,0.0,0,4,20,27,5,5,5,5,NaN,0
847330,59.166.0.8,48604,149.171.126.9,53,udp,CON,0.001035,146,178,31,29,0,0,dns,5.642512e+05,6.879228e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421962491,1421962491,0.004000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,4,1,1,4,2,1,1,NaN,0
2107055,59.166.0.1,34079,149.171.126.5,11680,tcp,FIN,0.660227,320,1938,31,29,1,2,ftp-data,3.235251e+03,2.055051e+04,6,8,255,255,4285543386,3537831876,53,242,0,0,9323.106880,230.584219,1424250302,1424250303,131.986600,94.250430,0.000611,0.000470,0.000141,0,0,NaN,NaN,,2,4,6,3,1,1,9,NaN,0
2535800,149.171.126.10,47439,175.45.176.0,53,udp,INT,0.000002,264,0,60,0,0,0,dns,5.280000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424261982,1424261982,0.002000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,30,30,12,12,12,12,30,NaN,0
1752965,59.166.0.0,7276,149.171.126.6,6881,tcp,FIN,4.088279,13142,548216,31,29,21,197,-,2.560491e+04,1.070309e+06,228,438,255,255,319461197,346677993,58,1252,0,0,6545.841441,4723.997980,1424240117,1424240122,18.008669,9.354254,0.000602,0.000467,0.000135,0,0,NaN,NaN,,3,3,2,2,2,1,2,NaN,0
1152347,175.45.176.3,58041,149.171.126.19,179,tcp,FIN,0.846008,534,268,254,252,2,1,-,4.548420e+03,2.118183e+03,10,6,255,255,216373059,3561041178,53,45,0,0,4815.651444,239.689312,1424223323,1424223324,87.795556,146.868594,0.219743,0.111656,0.108087,0,1,NaN,NaN,,2,1,1,2,1,1,1,NaN,0
42361,59.166.0.9,47341,149.171.126.3,53,udp,CON,0.001239,132,164,31,29,0,0,dns,4.261501e+05,5.294592e+05,2,2,0,0,0,0,66,82,0,0,0.000000,0.000000,1421929058,1421929058,0.010000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,3,1,3,2,1,1,1,NaN,0
1706010,149.171.126.18,47439,175.45.176.1,53,udp,INT,0.000008,264,0,60,0,0,0,dns,1.320000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424239013,1424239013,0.008000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,26,26,11,11,11,11,26,NaN,0
668336,59.166.0.5,53890,149.171.126.4,53,udp,CON,0.001019,132,164,31,29,0,0,dns,5.181551e+05,6.437684e+05,2,2,0,0,0,0,66,82,0,0,0.000000,0.000000,1421953662,1421953662,0.010000,0.001000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,3,2,1,7,1,1,1,NaN,0
1780218,59.166.0.1,49513,149.171.126.5,53,udp,CON,0.001067,132,164,31,29,0,0,dns,4.948454e+05,6.148079e+05,2,2,0,0,0,0,66,82,0,0,0.000000,0.000000,1424240778,1424240778,0.009000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,3,2,3,8,1,1,1,NaN,0
1847277,59.166.0.0,60459,149.171.126.9,22,tcp,FIN,0.645873,9400,12298,31,29,26,31,ssh,1.153416e+05,1.510018e+05,106,114,255,255,3144340227,995059021,89,108,0,0,331.545745,320.518520,1424243469,1424243469,6.207404,5.757170,0.001226,0.001064,0.000162,0,0,NaN,NaN,,1,1,1,3,1,1,1,NaN,0
176921,59.166.0.3,61621,149.171.126.9,111,udp,CON,0.122337,568,320,31,29,0,0,-,2.785748e+04,1.569435e+04,4,4,0,0,0,0,142,80,0,0,50.413887,34.384719,1421934035,1421934035,35.657000,24.324666,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,9,16,4,3,1,1,2,NaN,0
386792,59.166.0.0,18572,149.171.126.1,17943,tcp,FIN,0.025986,3806,52378,31,29,7,26,-,1.153544e+06,1.588086e+07,64,66,255,255,2727787588,582754572,59,794,0,0,21.601382,20.979802,1421943608,1421943608,0.413855,0.389169,0.000832,0.000680,0.000152,0,0,0.0,0.0,0,3,8,2,3,1,1,1,NaN,0
1250571,59.166.0.2,52469,149.171.126.5,21,tcp,FIN,0.844584,2934,3742,31,29,11,15,ftp,2.726076e+04,3.479109e+04,52,54,255,255,2375842574,231494192,56,69,0,0,1431.773786,52.821418,1424226108,1424226109,16.885461,15.925245,0.000680,0.000542,0.000138,0,0,NaN,1.0,1,1,1,2,2,1,1,5,NaN,0
783884,59.166.0.3,9752,149.171.126.7,45501,tcp,FIN,0.016200,2558,23470,31,29,7,14,-,1.232099e+06,1.131457e+07,40,42,255,255,3285950447,1155753871,64,559,0,0,0.000000,20.831464,1421959622,1421959622,0.406308,0.380951,0.000711,0.000578,0.000133,0,0,0.0,0.0,0,2,5,5,2,1,1,1,NaN,0

### 3. Datatypes of the features

In [13]:
df[['sport', 'dsport']] = df[['sport', 'dsport']].apply(
    pd.to_numeric, errors='coerce'
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype
---  ------            -----
 0   srcip             str
 1   sport             float64
 2   dstip             str
 3   dsport            float64
 4   proto             str
 5   state             str
 6   dur               float64
 7   sbytes            int64
 8   dbytes            int64
 9   sttl              int64
 10  dttl              int64
 11  sloss             int64
 12  dloss             int64
 13  service           str
 14  Sload             float64
 15  Dload             float64
 16  Spkts             int64
 17  Dpkts             int64
 18  swin              int64
 19  dwin              int64
 20  stcpb             int64
 21  dtcpb             int64
 22  smeansz           int64
 23  dmeansz           int64
 24  trans_depth       int64
 25  res_bdy_len       int64
 26  Sjit              float64
 27  Djit              float64
 28  Stime             int64
 29  Ltime             int64
 30  Sintpkt           float64
 31  Dintpkt           float64
 32  tcprtt            float64
 33  synack            float64
 34  ackdat            float64
 35  is_sm_ips_ports   int64
 36  ct_state_ttl      int64
 37  ct_flw_http_mthd  float64
 38  is_ftp_login      float64
 39  ct_ftp_cmd        object
 40  ct_srv_src        int64
 41  ct_srv_dst        int64
 42  ct_dst_ltm        int64
 43  ct_src_ ltm       int64
 44  ct_src_dport_ltm  int64
 45  ct_dst_sport_ltm  int64
 46  ct_dst_src_ltm    int64
 47  attack_cat        str
 48  Label             int64
dtypes: float64(14), int64(28), object(1), str(6)
memory usage: 949.6+ MB

### 2. Finding missing values

In [9]:
df['ct_ftp_cmd'].value_counts()

ct_ftp_cmd
     1429879
0    1066498
1      40077
2       1264
4        960
3        729
6        332
5        290
8         18
Name: count, dtype: int64

In [17]:
df['service'].value_counts()

service
-           1246397
dns          781668
http         206273
ftp-data     125783
smtp          81645
ftp           49090
ssh           47160
pop3           1533
dhcp            172
ssl             142
snmp            113
radius           40
irc              31
Name: count, dtype: int64

### 3. Handling missing values

In [10]:
df['service']=df['service'].replace(['-'], pd.NA)
df['service']=df['service'].fillna('unknown')

df['ct_ftp_cmd'] = df['ct_ftp_cmd'].replace([' '], pd.NA)
df['ct_ftp_cmd'] = df['ct_ftp_cmd'].fillna(0)

print(df[['service','ct_ftp_cmd','ct_flw_http_mthd', 'is_ftp_login']].sample(25))

          service ct_ftp_cmd  ct_flw_http_mthd  is_ftp_login
839086        dns          0               0.0           0.0
1145254      smtp          0               NaN           NaN
451360        ftp          1               0.0           1.0
2325169   unknown          0               NaN           NaN
1002022   unknown          0               0.0           0.0
1261337       dns          0               NaN           NaN
1039736      http          0               1.0           0.0
1843971   unknown          0               NaN           NaN
703453    unknown          0               0.0           0.0
161633    unknown          0               0.0           0.0
2043376   unknown          0               NaN           NaN
979941    unknown          0               0.0           0.0
42036        http          0               1.0           0.0
1086482      http          0               1.0           0.0
1571479   unknown          0               NaN           NaN
1111785   unknown          0               NaN           NaN
2507236      http          0               1.0           NaN
1036012       ftp          1               0.0           1.0
1234885  ftp-data          0               NaN           NaN
2489801       dns          0               NaN           NaN
375096       http          0               1.0           0.0
1551273   unknown          0               NaN           NaN
705261    unknown          0               0.0           0.0
1209727      http          0               1.0           NaN
660427    unknown          0               0.0           0.0

### 4. Dropping unnecessary features

In [11]:
data = df.copy()

data = data.drop(['srcip','dstip','dloss','sloss'],axis=1)
data.sample(10)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1376514,35671.0,10455.0,tcp,FIN,0.015930,2958,31784,31,29,unknown,1.454865e+06,1.564294e+07,48,50,255,255,2836114213,691014280,62,636,0,0,18.990584,18.463014,1424230547,1424230547,0.339174,0.320042,0.000700,0.000559,0.000141,0,0,NaN,NaN,0,1,2,2,1,1,1,1,NaN,0
1414137,1043.0,53.0,udp,INT,0.000009,114,0,254,0,dns,5.066666e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424231437,1424231437,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,0,39,39,22,22,21,21,40,Generic,1
990819,14594.0,80.0,tcp,FIN,1.010745,1684,10168,31,29,http,1.237899e+04,7.601521e+04,14,18,255,255,3191485217,3188383527,120,565,1,3924,8769.873792,7683.236621,1421968670,1421968671,77.721849,59.422820,0.000709,0.000553,0.000156,0,0,1.0,0.0,0,1,2,1,3,1,1,1,NaN,0
2384558,27320.0,47628.0,tcp,FIN,0.003959,424,8824,31,29,ftp-data,7.496842e+05,1.634554e+07,8,12,255,255,1632855388,3785089477,53,735,0,0,30.492840,18.594791,1424258373,1424258373,0.522286,0.316273,0.000599,0.000477,0.000122,0,0,NaN,NaN,0,3,3,8,5,1,1,4,NaN,0
125108,10371.0,8244.0,tcp,FIN,0.097864,3390,43544,31,29,unknown,2.722145e+05,3.498242e+06,56,58,255,255,4201849468,4252666170,61,751,0,0,96.293850,94.831006,1421932089,1421932089,1.772873,1.707561,0.000663,0.000529,0.000134,0,0,0.0,0.0,0,4,19,3,2,1,1,1,NaN,0
819745,7550.0,5807.0,tcp,FIN,0.047507,4030,55382,31,29,unknown,6.687014e+05,9.184836e+06,68,66,255,255,4202370907,4219101165,59,839,0,0,45.531293,46.331651,1421961205,1421961205,0.704358,0.723185,0.000652,0.000497,0.000155,0,0,0.0,0.0,0,8,5,3,5,1,1,1,NaN,0
1313058,30983.0,5190.0,tcp,FIN,0.004739,1470,1728,31,29,unknown,2.370120e+06,2.709432e+06,22,14,255,255,3669093466,3669366522,67,123,0,0,13.093775,0.456731,1424228641,1424228641,0.236950,0.313538,0.000638,0.000534,0.000104,0,0,NaN,NaN,0,8,2,4,8,1,1,2,NaN,0
2422229,45016.0,53.0,udp,CON,0.001061,130,162,31,29,dns,4.901037e+05,6.107446e+05,2,2,0,0,0,0,65,81,0,0,0.000000,0.000000,1424259221,1424259221,0.009000,0.002000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,1,2,2,3,1,1,1,NaN,0
2530640,1043.0,53.0,udp,INT,0.000003,264,0,60,0,dns,3.520000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424261862,1424261862,0.003000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,35,35,16,16,16,16,35,NaN,0
1376047,49077.0,53.0,udp,CON,0.000987,146,178,31,29,dns,5.916920e+05,7.213779e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424230539,1424230539,0.009000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,2,2,4,5,2,1,2,NaN,0

### 5. Sample of the cleaned data

In [12]:
data.sample(15)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1123285,43992.0,1938.0,tcp,FIN,0.048810,3598,48710,31,29,unknown,5.800451e+05,7.854948e+06,60,62,255,255,3994061458,1849001873,60,786,0,0,55.486283,54.110948,1424222439,1424222439,0.822017,0.803383,0.000735,0.000597,0.000138,0,0,NaN,NaN,0,7,12,7,4,1,1,3,NaN,0
1823376,57368.0,111.0,udp,CON,0.436171,568,304,31,29,unknown,7.813449e+03,4.181846e+03,4,4,0,0,0,0,142,76,0,0,180.536375,175.786516,1424242500,1424242500,127.663000,124.306336,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,7,3,3,2,1,1,3,NaN,0
58962,3450.0,46452.0,tcp,FIN,0.025998,3598,48710,31,29,unknown,1.089007e+06,1.474729e+07,60,62,255,255,1201668109,3347378749,60,786,0,0,24.447635,23.740385,1421929768,1421929768,0.434390,0.416082,0.000745,0.000606,0.000139,0,0,0.0,0.0,0,9,8,1,2,1,1,1,NaN,0
2243808,31194.0,111.0,udp,CON,0.004526,568,320,31,29,unknown,7.529828e+05,4.242157e+05,4,4,0,0,0,0,142,80,0,0,1.645674,1.432363,1424253685,1424253685,1.168667,1.016333,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,4,3,1,1,1,1,1,NaN,0
1192938,65372.0,39858.0,tcp,FIN,0.021908,2974,33572,31,29,unknown,1.063721e+06,1.201424e+07,48,50,255,255,3068118853,923063694,62,671,0,0,25.657131,25.486096,1424224420,1424224420,0.459553,0.442750,0.000790,0.000647,0.000143,0,0,NaN,NaN,0,7,4,3,4,1,1,2,NaN,0
1960474,47439.0,53.0,udp,INT,0.000001,264,0,60,0,dns,1.056000e+09,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424246098,1424246098,0.001000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,29,29,29,29,29,12,29,NaN,0
2252530,23011.0,61092.0,tcp,FIN,0.011893,2542,23354,31,29,unknown,1.667536e+06,1.533541e+07,40,42,255,255,2356989196,207721400,64,556,0,0,17.919738,16.534480,1424253897,1424253897,0.304526,0.275244,0.000725,0.000599,0.000126,0,0,NaN,NaN,0,5,2,2,4,1,1,1,NaN,0
1507143,33459.0,5190.0,tcp,FIN,0.005595,1958,2308,31,29,unknown,2.672386e+06,3.162824e+06,22,24,255,255,1475933795,3621633736,89,96,0,0,15.272997,12.925424,1424233330,1424233330,0.250143,0.216217,0.000735,0.000613,0.000122,0,0,NaN,NaN,0,7,2,3,1,1,1,2,NaN,0
2311805,54760.0,17562.0,tcp,FIN,0.224278,8928,320,31,29,ftp-data,2.957401e+05,9.523895e+03,14,6,255,255,1883366603,2412974013,638,53,0,0,1574.607405,67.166891,1424255204,1424255204,17.252154,44.695602,0.001392,0.000677,0.000715,0,0,NaN,NaN,0,2,1,6,4,1,1,2,NaN,0
2377801,54393.0,80.0,tcp,FIN,1.209077,1684,10168,31,29,http,1.034839e+04,6.354600e+04,14,18,255,255,2373640775,2370400162,120,565,1,3924,9325.892494,8168.532463,1424258088,1424258090,92.979921,71.091471,0.000648,0.000521,0.000127,0,0,1.0,NaN,0,4,4,6,5,1,1,2,NaN,0
1852980,40179.0,11269.0,tcp,FIN,0.330078,4552,2976,31,29,unknown,1.063991e+05,6.955931e+04,28,28,255,255,2538744701,396459916,163,106,0,0,727.214197,19.380697,1424243707,1424243708,12.213593,12.207148,0.000606,0.000480,0.000126,0,0,NaN,NaN,0,19,5,1,6,1,1,5,NaN,0
135573,47439.0,53.0,udp,INT,0.000010,114,0,254,0,dns,4.560000e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1421932449,1421932449,0.010000,0.000000,0.000000,0.000000,0.000000,0,2,0.0,0.0,0,16,16,7,7,7,4,7,Generic,1
1022198,4936.0,21.0,tcp,FIN,0.024956,2934,3740,31,29,ftp,9.225838e+05,1.176791e+06,52,54,255,255,342887698,343970925,56,69,0,0,33.000788,0.823864,1421969979,1421969979,0.483274,0.461528,0.000628,0.000491,0.000137,0,0,0.0,1.0,1,1,1,7,5,1,1,4,NaN,0
1151593,47439.0,53.0,udp,INT,0.000009,114,0,254,0,dns,5.066666e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424223305,1424223305,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,0,22,22,8,8,8,8,22,Generic,1
1973640,27648.0,6881.0,tcp,FIN,0.219834,1540,1644,31,29,unknown,5.254874e+04,5.651537e+04,16,18,255,255,3887228547,1780517819,96,91,0,0,1083.518453,22.746809,1424246290,1424246291,14.633533,12.867588,0.001204,0.001081,0.000123,0,0,NaN,NaN,0,7,8,11,5,5,1,5,NaN,0