## Data Preprocessing

### 1. Load the libraries

In [2]:
import pandas as pd

### 2. Load the dataset

In [3]:
df = pd.read_csv(r'C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\UNSW-NB15.csv', low_memory=False)
pd.set_option('display.max_columns', None)
df.sample(15)

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
2201336,149.171.126.14,1043,175.45.176.1,53,udp,INT,0.000004,264,0,60,0,0,0,dns,2.640000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424252900,1424252900,0.004000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,42,42,42,42,42,23,42,NaN,0
1098181,59.166.0.9,49271,149.171.126.8,6881,tcp,FIN,1.453494,13974,548216,31,29,21,197,-,7.659888e+04,3.010484e+06,244,438,255,255,1326090061,1344578987,57,1252,0,0,370.692190,262.121872,1424220230,1424220231,5.980140,3.324858,0.000651,0.000524,0.000127,0,0,NaN,NaN,,8,6,1,1,1,1,5,NaN,0
21948,59.166.0.6,59258,149.171.126.0,6881,tcp,FIN,0.175950,1540,1644,31,29,4,4,-,6.565502e+04,7.061097e+04,16,18,255,255,382228037,2579505571,96,91,0,0,780.854390,24.857941,1421928246,1421928246,11.708733,10.318706,0.000886,0.000531,0.000355,0,0,0.0,0.0,0,7,13,9,7,5,1,6,NaN,0
1835603,59.166.0.7,44976,149.171.126.6,45700,tcp,FIN,0.410280,4840,3080,31,29,7,7,-,9.102077e+04,5.806766e+04,28,30,255,255,2834636364,813454769,173,103,0,0,879.352169,22.719402,1424242985,1424242986,15.183741,14.128552,0.000680,0.000549,0.000131,0,0,NaN,NaN,,3,4,1,1,1,1,8,NaN,0
1166472,59.166.0.1,44063,149.171.126.6,42102,tcp,FIN,0.029642,4134,62112,31,29,7,30,-,1.099791e+06,1.653680e+07,70,74,255,255,211720712,2371766209,59,839,0,0,22.944361,0.000000,1424223649,1424223649,0.424609,0.398616,0.000705,0.000540,0.000165,0,0,NaN,NaN,,3,1,2,5,1,1,1,NaN,0
619059,59.166.0.3,35639,149.171.126.9,12406,tcp,FIN,0.010902,2438,18678,31,29,7,13,-,1.742066e+06,1.336415e+07,38,40,255,255,3188666662,3197999586,64,467,0,0,0.000000,16.520417,1421951461,1421951461,0.285757,0.271921,0.000699,0.000566,0.000133,0,0,0.0,0.0,0,7,10,2,10,1,1,1,NaN,0
1670750,175.45.176.1,47439,149.171.126.18,53,udp,INT,0.000009,114,0,254,0,0,0,dns,5.066666e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424238342,1424238342,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,,44,44,44,44,44,20,44,Generic,1
1009031,59.166.0.8,3187,149.171.126.1,80,tcp,FIN,0.003898,1044,824,31,29,2,2,http,1.875834e+06,1.522832e+06,8,10,255,255,1240532441,1241525195,131,82,1,83,32.521448,0.683513,1421969465,1421969465,0.505000,0.378667,0.000619,0.000485,0.000134,0,0,2.0,0.0,0,2,3,3,10,1,1,1,NaN,0
76202,59.166.0.1,18396,149.171.126.0,5190,tcp,FIN,0.594981,2814,17186,31,29,8,11,-,3.684151e+04,2.242895e+05,38,34,255,255,784808765,785113130,74,505,0,0,2154.087101,2283.900543,1421930454,1421930455,16.080568,18.006031,0.000809,0.000633,0.000176,0,0,0.0,0.0,0,8,9,2,5,1,1,1,NaN,0
146984,59.166.0.7,54611,149.171.126.4,60872,tcp,FIN,0.037238,3390,40986,31,29,7,22,-,7.153982e+05,8.653526e+06,56,58,255,255,1828315962,1835665044,61,707,0,0,0.000000,47.385857,1421932865,1421932865,0.653327,0.644579,0.000640,0.000493,0.000147,0,0,0.0,0.0,0,4,10,3,2,1,1,1,NaN,0
1677464,149.171.126.18,1043,175.45.176.1,53,udp,INT,0.000002,264,0,60,0,0,0,dns,5.280000e+08,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424238497,1424238497,0.002000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,14,14,14,14,14,14,14,NaN,0
2293320,149.171.126.14,1043,175.45.176.1,53,udp,INT,0.000001,264,0,60,0,0,0,dns,1.056000e+09,0.000000e+00,2,0,0,0,0,0,132,0,0,0,0.000000,0.000000,1424254850,1424254850,0.001000,0.000000,0.000000,0.000000,0.000000,0,0,NaN,NaN,,17,17,17,17,17,17,17,NaN,0
111204,59.166.0.4,30235,149.171.126.0,53,udp,CON,0.000945,146,178,31,29,0,0,dns,6.179894e+05,7.534392e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421931604,1421931604,0.011000,0.002000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,2,4,2,2,2,1,1,NaN,0
1933417,175.45.176.3,1043,149.171.126.15,53,udp,INT,0.000009,114,0,254,0,0,0,dns,5.066666e+07,0.000000e+00,2,0,0,0,0,0,57,0,0,0,0.000000,0.000000,1424245681,1424245681,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,,34,34,22,24,22,22,34,Generic,1
921428,59.166.0.1,15465,149.171.126.5,80,tcp,FIN,1.267972,1684,10168,31,29,3,5,http,9.867726e+03,6.059440e+04,14,18,255,255,2332767807,2356541050,120,565,1,3924,8898.172603,7791.835477,1421965490,1421965491,97.507541,74.555176,0.000664,0.000530,0.000134,0,0,1.0,0.0,0,2,2,3,2,1,1,1,NaN,0

### 3. Datatypes of the features

In [4]:
df[['sport', 'dsport']] = df[['sport', 'dsport']].apply(
    pd.to_numeric, errors='coerce'
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype
---  ------            -----
 0   srcip             str
 1   sport             float64
 2   dstip             str
 3   dsport            float64
 4   proto             str
 5   state             str
 6   dur               float64
 7   sbytes            int64
 8   dbytes            int64
 9   sttl              int64
 10  dttl              int64
 11  sloss             int64
 12  dloss             int64
 13  service           str
 14  Sload             float64
 15  Dload             float64
 16  Spkts             int64
 17  Dpkts             int64
 18  swin              int64
 19  dwin              int64
 20  stcpb             int64
 21  dtcpb             int64
 22  smeansz           int64
 23  dmeansz           int64
 24  trans_depth       int64
 25  res_bdy_len       int64
 26  Sjit              float64
 27  Djit              float64
 28  Stime             int64
 29  Ltime             int64
 30  Sintpkt           float64
 31  Dintpkt           float64
 32  tcprtt            float64
 33  synack            float64
 34  ackdat            float64
 35  is_sm_ips_ports   int64
 36  ct_state_ttl      int64
 37  ct_flw_http_mthd  float64
 38  is_ftp_login      float64
 39  ct_ftp_cmd        str
 40  ct_srv_src        int64
 41  ct_srv_dst        int64
 42  ct_dst_ltm        int64
 43  ct_src_ ltm       int64
 44  ct_src_dport_ltm  int64
 45  ct_dst_sport_ltm  int64
 46  ct_dst_src_ltm    int64
 47  attack_cat        str
 48  Label             int64
dtypes: float64(14), int64(28), str(7)
memory usage: 949.6 MB

### 2. Finding abnormal values

In [5]:
df['ct_ftp_cmd'].value_counts()

ct_ftp_cmd
     1429879
0    1066498
1      40077
2       1264
4        960
3        729
6        332
5        290
8         18
Name: count, dtype: int64

In [6]:
df['service'].value_counts()

service
-           1246397
dns          781668
http         206273
ftp-data     125783
smtp          81645
ftp           49090
ssh           47160
pop3           1533
dhcp            172
ssl             142
snmp            113
radius           40
irc              31
Name: count, dtype: int64

In [7]:
df['attack_cat'].value_counts()

attack_cat
Generic             215481
Exploits             44525
 Fuzzers             19195
DoS                  16353
 Reconnaissance      12228
 Fuzzers              5051
Analysis              2677
Backdoor              1795
Reconnaissance        1759
 Shellcode            1288
Backdoors              534
Shellcode              223
Worms                  174
Name: count, dtype: int64

### 3. Handling abnormal values

In [8]:
df['service']=df['service'].replace(['-'], pd.NA)
df['service']=df['service'].fillna('unknown')

df['ct_ftp_cmd'] = df['ct_ftp_cmd'].replace([' '], pd.NA)
df['ct_ftp_cmd'] = df['ct_ftp_cmd'].fillna(0)

df['attack_cat'] = df['attack_cat'].fillna('Normal')
df['attack_cat'] = df['attack_cat'].str.strip()
df["attack_cat"] = df["attack_cat"].replace({
    "Backdoors": "Backdoor"
})

print(df[['service','ct_ftp_cmd','attack_cat']].sample(25),"\n")
df['attack_cat'].value_counts()

          service ct_ftp_cmd attack_cat
1439000       ssh          0     Normal
203169    unknown          0     Normal
279102    unknown          0     Normal
1959596       dns          0     Normal
2389280       dns          0     Normal
2305919       dns          0    Generic
372508        ftp          1     Normal
875149        dns          0     Normal
269653    unknown          0     Normal
1363542   unknown          0     Normal
2252583      http          0     Normal
1189998       dns          0     Normal
1541908   unknown          0     Normal
2155646       dns          0     Normal
2099957   unknown          0     Normal
1831747  ftp-data          0     Normal
1815361  ftp-data          0     Normal
1781691       dns          0     Normal
1179141   unknown          0     Normal
2517906       dns          0     Normal
488564    unknown          0     Normal
1762824       dns          0    Generic
1187998   unknown          0     Normal
1487914   unknown          0    Fuzzers
605507        dns          0     Normal

attack_cat
Normal            2218764
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoor             2329
Shellcode            1511
Worms                 174
Name: count, dtype: int64

### 4. Dropping unnecessary features

In [9]:
data = df.copy()

data = data.drop(['srcip','dstip','dloss','sloss'],axis=1)
data.sample(10)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1615186,61215.0,6881.0,tcp,FIN,9.699767,7012,266628,31,29,unknown,5.733746e+03,2.189059e+05,116,220,255,255,3763756447,1684632504,60,1212,0,0,26038.052580,18864.773240,1424237145,1424237155,84.342579,44.288905,0.000604,0.000492,0.000112,0,0,NaN,NaN,0,6,6,5,2,2,1,3,Normal,0
1197818,31553.0,53.0,udp,CON,0.001097,146,178,31,29,dns,5.323610e+05,6.490429e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1424224532,1424224532,0.009000,0.007000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,1,2,1,2,1,1,1,Normal,0
1874663,0.0,0.0,unas,INT,0.000009,200,0,254,0,unknown,8.888889e+07,0.000000e+00,2,0,0,0,0,0,100,0,0,0,0.000000,0.000000,1424244428,1424244428,0.009000,0.000000,0.000000,0.000000,0.000000,0,2,NaN,NaN,0,12,12,4,4,4,4,14,Exploits,1
486019,63974.0,5190.0,tcp,FIN,0.284014,4908,2344,31,29,unknown,1.341906e+05,6.329266e+04,34,24,255,255,476592442,476905718,144,98,0,0,782.853993,26.837887,1421945619,1421945619,8.606485,12.319174,0.000652,0.000536,0.000116,0,0,0.0,0.0,0,14,13,15,19,3,3,8,Normal,0
2105757,12501.0,9942.0,tcp,FIN,0.016008,2542,22128,31,29,unknown,1.238880e+06,1.079560e+07,40,42,255,255,3630310417,3630588779,64,527,0,0,28.210785,27.329834,1424250248,1424250248,0.402410,0.386325,0.000664,0.000549,0.000115,0,0,NaN,NaN,0,4,1,1,5,1,1,1,Normal,0
1583742,50100.0,5190.0,tcp,FIN,0.006262,1920,4312,31,29,unknown,2.341744e+06,5.280102e+06,22,24,255,255,1404863129,1405122753,87,180,0,0,17.765272,13.657205,1424235831,1424235831,0.281905,0.249957,0.000620,0.000507,0.000113,0,0,NaN,NaN,0,4,3,1,3,1,1,1,Normal,0
675196,3892.0,53.0,udp,CON,0.001109,146,178,31,29,dns,5.266006e+05,6.420199e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421953929,1421953929,0.011000,0.008000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,3,3,2,2,1,1,1,Normal,0
2528571,5903.0,6881.0,tcp,FIN,0.017816,1540,1644,31,29,unknown,6.484059e+05,6.973507e+05,16,18,255,255,1973588390,4124013179,96,91,0,0,70.520826,1.998487,1424261817,1424261817,1.167533,1.021000,0.000586,0.000456,0.000130,0,0,NaN,NaN,0,7,15,7,9,6,1,6,Normal,0
228977,13019.0,31677.0,tcp,FIN,0.002942,320,1816,31,29,ftp-data,7.260367e+05,4.320870e+06,6,8,255,255,201174380,2350320366,53,227,0,0,29.563147,0.566369,1421936223,1421936223,0.523400,0.354286,0.000600,0.000458,0.000142,0,0,0.0,0.0,0,3,3,6,6,1,1,5,Normal,0
1821809,42813.0,111.0,udp,CON,0.004507,568,304,31,29,unknown,7.561571e+05,4.047038e+05,4,4,0,0,0,0,142,76,0,0,1.678672,1.421285,1424242444,1424242444,1.194000,1.011000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,4,5,5,4,1,1,4,Normal,0

### 5. Drop Duplicates

In [10]:
data = data.drop_duplicates()
print(data.duplicated().sum())

0

### 6. Sample of the cleaned data

In [11]:
data.sample(15)

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,service,Sload,Dload,Spkts,Dpkts,swin,dwin,stcpb,dtcpb,smeansz,dmeansz,trans_depth,res_bdy_len,Sjit,Djit,Stime,Ltime,Sintpkt,Dintpkt,tcprtt,synack,ackdat,is_sm_ips_ports,ct_state_ttl,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
998080,34281.0,38904.0,tcp,FIN,0.064186,3390,44906,31,29,unknown,4.150438e+05,5.500514e+06,56,58,255,255,3188863976,3207682060,61,774,0,0,0.000000,71.245994,1421969014,1421969014,1.161000,1.116123,0.000695,0.000563,0.000132,0,0,0.0,0.0,0,7,4,4,4,1,1,2,Normal,0
269534,37395.0,14003.0,tcp,FIN,0.107862,3806,53008,31,29,unknown,2.779107e+05,3.871984e+06,64,66,255,255,2069805064,4276757910,59,803,0,0,91.297095,90.032461,1421938116,1421938116,1.705317,1.650800,0.000696,0.000556,0.000140,0,0,0.0,0.0,0,2,11,4,2,1,1,1,Normal,0
180067,38269.0,39113.0,tcp,FIN,0.983236,4560,3080,31,29,unknown,3.578388e+04,2.423020e+04,28,30,255,255,1836786721,1946025436,163,103,0,0,2059.874180,53.111328,1421934172,1421934173,36.403776,33.885656,0.000700,0.000551,0.000149,0,0,0.0,0.0,0,7,10,2,2,1,1,1,Normal,0
515604,28395.0,52071.0,tcp,FIN,0.022921,2974,31816,31,29,unknown,1.016710e+06,1.087352e+07,48,48,255,255,3631798825,3632108302,62,663,0,0,26.988434,26.338061,1421946852,1421946852,0.480915,0.475085,0.000735,0.000584,0.000151,0,0,0.0,0.0,0,9,7,1,4,1,1,1,Normal,0
2263362,21133.0,19255.0,tcp,FIN,0.089992,4862,82278,31,29,unknown,4.271491e+05,7.229264e+06,84,86,255,255,1701235845,3862469080,58,957,0,0,69.392754,68.234811,1424254190,1424254190,1.093537,1.065333,0.000632,0.000501,0.000131,0,0,NaN,NaN,0,6,4,2,4,1,1,1,Normal,0
1430323,12791.0,22.0,tcp,FIN,0.006197,3728,5474,31,29,ssh,4.662902e+06,6.772310e+06,32,24,255,255,2656838601,2661296060,117,228,0,0,12.566953,0.350649,1424231800,1424231800,0.199903,0.240000,0.000691,0.000565,0.000126,0,0,NaN,NaN,0,1,1,1,4,1,1,2,Normal,0
757472,60281.0,80.0,tcp,FIN,1.006062,1684,10168,31,29,http,1.243661e+04,7.636905e+04,14,18,255,255,4250784015,2106592472,120,565,1,3924,8764.561245,7673.682034,1421958492,1421958493,77.361690,59.152471,0.000587,0.000466,0.000121,0,0,1.0,0.0,0,1,3,2,8,1,1,1,Normal,0
902635,14393.0,5190.0,tcp,FIN,2.685557,3022,17186,31,29,unknown,8.790728e+03,4.969100e+04,42,34,255,255,186035133,186639893,72,505,0,0,4433.931122,132.552391,1421964649,1421964652,65.501389,81.341063,0.001294,0.001170,0.000124,0,0,0.0,0.0,0,5,8,7,3,1,1,1,Normal,0
2314490,3371.0,48124.0,tcp,FIN,0.872438,5064,3080,31,29,unknown,4.478484e+04,2.730738e+04,28,30,255,255,763627484,920799838,181,103,0,0,1984.758905,52.335133,1424255258,1424255259,32.299852,30.064518,0.000748,0.000564,0.000184,0,0,NaN,NaN,0,4,4,5,5,1,1,3,Normal,0
547552,19615.0,44539.0,tcp,FIN,0.004088,8928,320,31,29,ftp-data,1.622505e+07,5.225049e+05,14,6,255,255,3779315563,3794248530,638,53,0,0,19.259111,1.248409,1421948320,1421948320,0.314462,0.693000,0.000637,0.000493,0.000144,0,0,0.0,0.0,0,3,3,5,6,1,1,5,Normal,0
1194459,58572.0,3260.0,tcp,CON,0.232737,986,86,62,252,unknown,2.825507e+04,1.478063e+03,6,2,255,255,1093043607,1597520778,164,43,0,0,3018.837451,0.000000,1424224460,1424224460,46.547400,0.002000,0.212532,0.101927,0.110605,0,3,NaN,NaN,0,7,7,4,5,4,1,7,Normal,0
1439789,45221.0,2612.0,tcp,FIN,0.035883,4118,57846,31,29,unknown,9.051641e+05,1.271243e+07,70,70,255,255,2029522741,2029793334,59,826,0,0,31.573489,0.840604,1424231927,1424231928,0.515362,0.512623,0.000624,0.000502,0.000122,0,0,NaN,NaN,0,2,5,4,2,1,1,2,Normal,0
1323344,29115.0,111.0,udp,CON,0.272216,568,312,31,29,unknown,1.251947e+04,6.876892e+03,4,4,0,0,0,0,142,78,0,0,109.827828,121.537516,1424229016,1424229016,77.665000,85.945000,0.000000,0.000000,0.000000,0,0,NaN,NaN,0,15,9,3,10,2,1,3,Normal,0
1518718,31571.0,2431.0,tcp,FIN,0.025892,3718,43716,31,29,unknown,1.130542e+06,1.328936e+07,62,62,255,255,1452076901,1452967700,60,705,0,0,23.150096,0.577577,1424233580,1424233580,0.419311,0.414311,0.000775,0.000604,0.000171,0,0,NaN,NaN,0,3,3,1,3,1,1,2,Normal,0
499299,59670.0,53.0,udp,CON,0.001020,146,178,31,29,dns,5.725491e+05,6.980392e+05,2,2,0,0,0,0,73,89,0,0,0.000000,0.000000,1421946133,1421946133,0.010000,0.002000,0.000000,0.000000,0.000000,0,0,0.0,0.0,0,3,2,4,3,2,1,1,Normal,0

### 7. Save the dataset

In [13]:
data.to_csv(r"C:\Users\HP\Documents\PycharmProjects\network-anomaly-detector\Detector\data\processed-data\clean-data.csv", index=False)